### ISSUE TITLE
Just another an issue. 

### ISSUE THREAD

**Issue by Danila24ru** [KillaMaaki/Unity-Netcode.IO#3]
https://github.com/KillaMaaki/Unity-Netcode.IO/blob/808d7c03c275b5d161124ab81a782770533da973/Assets/UnityNetcodeIO/Scripts/Core/UnityNetcode.cs#L90

ByteBuffer doesn't contain .MemoryCopy() function.

**Comment by GlaireDaggers** [comment]
GAH. I always miss the little things like this.
Added back in the MemoryCopy function (just does a simple per-byte copy from a pointer). Thought it was unused but ofc didn't check and see if it broke in WebGL (and the ifdef meant it didn't immediately throw a compiler error in Unity).
Latest commit should fix.
