### ISSUE TITLE
Unable to connect with Golang created Token

### ISSUE THREAD

**Issue by SonarBeserk** [KillaMaaki/Unity-Netcode.IO#5]
Using the server at https://github.com/wirepair/netcode/blob/master/examples/server/server.go I have issues try to connect with the token it generates. I have converted the token from Base64 but get an invalid format exception. Is that something that the latest changes in Netcode.IO.NET would fix?

**Comment by nokrosis** [comment]
¿Did you get it to work? I have the same setup and getting Invalid Token without conversion and Invalid Format after Base64 conversion.

**Comment by SonarBeserk** [comment]
I had to make an adjustment in code as noted in https://github.com/KillaMaaki/Netcode.IO.NET/issues/16. I also had issues with ipv6 I never resolved. I moved onto a different library due to inactivity around this library.

**Comment by nokrosis** [comment]
Which library did you end up using?

**Comment by SonarBeserk** [comment]
https://github.com/obsilp/rmnp-csharp I use c# for the client and https://github.com/obsilp/rmnp for the server. Needs a little work and adjustments of course but everything does
